name: NHD_SignIn

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
  schedule:
    - cron: 0 4 * * *
  pull_request:
    branches: [ master ]
  watch:
    types: [started]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python3
        uses: actions/setup-python@master
      - name: Install packages
        run: |
          pip3 install selenium requests
      - name: Run script
        env:
          WEBVPNACCOUNT: ${{ secrets.WEBVPNACCOUNT }}
          WEBVPNPASSWORD: ${{ secrets.WEBVPNPASSWORD }}
          NHDACCOUNT: ${{ secrets.NHDACCOUNT }}
          NHDPASSWORD: ${{ secrets.NHDPASSWORD }}
          SCKEY: ${{ secrets.SCKEY }}
        run: |
          python3 script.py ${WEBVPNACCOUNT} ${WEBVPNPASSWORD} ${NHDACCOUNT} ${NHDPASSWORD} ${SCKEY}
