name: NHD_SignIn

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python3
        uses: actions/setup-python@master
      - name: Install packages
        run: |
          pip3 install selenium
      - name: Run a multi-line script
        env:
          WEBVPNACCOUNT: ${{ secrets.WEBVPNACCOUNT }}
          WEBVPNPASSWORD: ${{ secrets.WEBVPNPASSWORD }}
          NHDACCOUNT: ${{ secrets.NHDACCOUNT }}
          NHDPASSWORD: ${{ secrets.NHDPASSWORD }}
          SCKEY: ${{ secrets.SCKEY }}
        run: |
          python3 test.py ${WEBVPNACCOUNT} ${WEBVPNPASSWORD} ${NHDACCOUNT} ${NHDPASSWORD} ${SCKEY}
